### ISSUE TITLE
APIKey y Shared Secret

### ISSUE THREAD

**Issue by R3yes** [TransbankDevelopers/transbank-plugin-woocommerce-onepay#19]
al momento de realizar el pago con onepay en woocommerce nos arroja el mensaje Operación cancelada, sera posible que sea por la APIKey y Shared Secret, ¿y si es posible enviarnos las correctas?.

**Comment by RodrigoAyala** [comment]
Hola @R3yes, a futuro no será necesario ingresar APIKey y Shared Secret para realizar pruebas en ambiente de integración. Por ahora ocupa las credenciales de prueba que se encuentran en el manual de instalación, específicamente en https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-onepay/blob/master/docs/INSTALLATION.md#credenciales-de-prueba

**Comment by RodrigoAyala** [comment]
@R3yes cerraré este Issue, asumiendo que mi respuesta anterior resolvió tu duda. Si necesitas ayuda, coméntanos nuevamente.
