### ISSUE TITLE
Wrong function called in healthcheck.php, line 457

### ISSUE THREAD

**Issue by eperezf** [TransbankDevelopers/transbank-plugin-woocommerce-onepay#27]
Line 457 says:
$env = $this->getEcommerceInfo();

Should be:
$env = $this->getCommerceInfo();

**Comment by eperezf** [comment]
Wrong plugin.

**Comment by leosoto** [comment]
Which plugin are you referring to ?

**Comment by eperezf** [comment]
WooCommerce WebPay plugin
