### ISSUE TITLE
Cambiar el prefijo enduro a variable

### ISSUE THREAD

**Issue by Rodolfox1** [TransbankDevelopers/transbank-plugin-woocommerce-onepay#47]
**Describe el bug**

Al momento de volver a la url de callback, el plugin consulta a la base de datos usando el prefijo enduro en la tabla. 

**Para reproducir**

1. Configura 'includes/class-onepay.php'
2. Baja hasta la linea 182
3. Cambiar el prefijo 'wp_' por una concatenación de $wpdb->prefix

**Comportamiento observado**

error al no hacer coincidir el nombre de la tabla de base de datos

**Comportamiento esperado**

que la consulta sea exitosa utilizando el prefijo guardado en las config

**Versiones (por favor agrega aquí la siguiente información):**
- Plugin: onepay 1.1.2
- Woocommerce: 3.8.1
- PHP: 7.2

**Comment by gdespirito** [comment]
Gracias por el issue. Tienes razón.
¿Te interesa enviar un Pull Request con este fix? Así quedarás como autor y contribuidor del repositorio. 
Si necesitas ayuda para hacerlo, te podemos apoyar.

**Comment by Rodolfox1** [comment]
> Gracias por el issue. Tienes razón.
> ¿Te interesa enviar un Pull Request con este fix? Así quedarás como autor y contribuidor del repositorio.
> Si necesitas ayuda para hacerlo, te podemos apoyar.

Si, me podrías ayudar. 
Gracias.

**Comment by gdespirito** [comment]
Perfecto, para crear un Pull Request debes eguir este procedimiento:

1. - [Hacer un fork](https://help.github.com/es/github/getting-started-with-github/fork-a-repo) de este repositorio. Esto creará una copia en tu propia cuenta de github. 
2. - Descargar/clonar este nuevo repositorio en tu computador
3. - Crear un nuevo branch (algo como `fix/database_prefix`)
4. - Hacer los cambios necesarios en ese branch, hacer commit y subir el branch a tu repositorio (`git push ...`)
5. -  Si ya tienes un branch creado en tu fork, ya puedes hacer un Pull Request en este repositorio siguiendo [estas instrucciones](https://help.github.com/es/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

Si tienes dudas, puedes hablarme por el slack de la comunidad de TransbankDevelopers. Puedes unirte acá: https://join-transbankdevelopers-slack.herokuapp.com/

**Comment by gdespirito** [comment]
I saw you created https://github.com/TransbankDevelopers/transbank-plugin-woocommerce-onepay/pull/48. As this is merged, i'm closing this issue 👌 
Thanks for your help!

**Comment by gdespirito** [comment]
This will be available on the next release of the plugin, probably this or next week.
